# Generated by Django 3.2.6 on 2021-08-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['poll_id'], 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created',
        ),
    ]
